name: Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual run in Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4 # ✅ use v4!
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
